  version: '3.8'

  services:
    e-com-academy:
      build: .
      ports:
        - "8080:8080"
      container_name: e-com-academy-container
      restart: unless-stopped
      environment:
        - NODE_ENV=production
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge
      